CREATE VIEW OWNERS_ZONES_RENTED 
AS SELECT OWNERS.NAME, COUNT(*) ZONES_RENTED, SUM(PRICE) TOTAL_RENT FROM CONTRACTS LEFT JOIN OWNERS ON contracts.OWNER = owners.OWNER_ID GROUP BY OWNERS.NAME;

CREATE VIEW STAFF_BY_DEP AS
SELECT s.DEP, COUNT(*) STAFF_COUNT FROM STAFF s GROUP BY s.DEP;

SELECT * FROM OWNERS_ZONES_RENTED;
SELECT * FROM STAFF_BY_DEP;