CREATE TRIGGER DEFAULT_CONTRACT_START
NO CASCADE BEFORE INSERT ON CONTRACTS
REFERENCING NEW AS n
FOR EACH ROW
MODE DB2SQL 
WHEN(n.stdate IS NULL) SET n.stdate = CURRENT TIMESTAMP;

CREATE TRIGGER DEFAULT_CONTRACT_END
NO CASCADE BEFORE INSERT ON CONTRACTS
REFERENCING NEW AS n
FOR EACH ROW
MODE DB2SQL 
WHEN(n.endate IS NULL) SET n.endate = n.stdate + 1 DAY;